//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gaussians.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gaussians.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Approximation.
        /// </summary>
        public static string ApproximationOperations {
            get {
                return ResourceManager.GetString("ApproximationOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Read other file.
        /// </summary>
        public static string ByPatternReaderName {
            get {
                return ResourceManager.GetString("ByPatternReaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на #ff000000
        ///#ff0000ff
        ///#ff00ff00
        ///#ffff0000
        ///#fff000f0
        ///#ff00f0f0
        ///#ff00ffff.
        /// </summary>
        public static string ColorsForGraphs {
            get {
                return ResourceManager.GetString("ColorsForGraphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export.
        /// </summary>
        public static string ExportGraphOperations {
            get {
                return ResourceManager.GetString("ExportGraphOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show graph.
        /// </summary>
        public static string FunctionNodeShowGraphName {
            get {
                return ResourceManager.GetString("FunctionNodeShowGraphName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Graph.
        /// </summary>
        public static string FunctionParameterGraph {
            get {
                return ResourceManager.GetString("FunctionParameterGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Find Gaussian.
        /// </summary>
        public static string GraphGaussianFinders {
            get {
                return ResourceManager.GetString("GraphGaussianFinders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Properties.
        /// </summary>
        public static string GraphProperties {
            get {
                return ResourceManager.GetString("GraphProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add operation.
        /// </summary>
        public static string MenuAddOperations {
            get {
                return ResourceManager.GetString("MenuAddOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Import.
        /// </summary>
        public static string MenuImportFile {
            get {
                return ResourceManager.GetString("MenuImportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Insert operation.
        /// </summary>
        public static string MenuInsertOperations {
            get {
                return ResourceManager.GetString("MenuInsertOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open.
        /// </summary>
        public static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Operations.
        /// </summary>
        public static string MenuOperations {
            get {
                return ResourceManager.GetString("MenuOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string MenuSave {
            get {
                return ResourceManager.GetString("MenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Graph changer.
        /// </summary>
        public static string OperationGraphChangers {
            get {
                return ResourceManager.GetString("OperationGraphChangers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Inputs.
        /// </summary>
        public static string OperationInputs {
            get {
                return ResourceManager.GetString("OperationInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Run.
        /// </summary>
        public static string OperationInvoke {
            get {
                return ResourceManager.GetString("OperationInvoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Outputs.
        /// </summary>
        public static string OperationOutputs {
            get {
                return ResourceManager.GetString("OperationOutputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string OperationPropertyName {
            get {
                return ResourceManager.GetString("OperationPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value.
        /// </summary>
        public static string OperationPropertyValue {
            get {
                return ResourceManager.GetString("OperationPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove.
        /// </summary>
        public static string OperationRemove {
            get {
                return ResourceManager.GetString("OperationRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Graph.
        /// </summary>
        public static string ReaderGraphName {
            get {
                return ResourceManager.GetString("ReaderGraphName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Read graph.
        /// </summary>
        public static string ReadGraphOperations {
            get {
                return ResourceManager.GetString("ReadGraphOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color.
        /// </summary>
        public static string SettingColorGraph {
            get {
                return ResourceManager.GetString("SettingColorGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string SettingNameGraph {
            get {
                return ResourceManager.GetString("SettingNameGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove.
        /// </summary>
        public static string SettingRemoveGraph {
            get {
                return ResourceManager.GetString("SettingRemoveGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Smoothing.
        /// </summary>
        public static string SmoothingOperations {
            get {
                return ResourceManager.GetString("SmoothingOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] UnvisibleGraph {
            get {
                object obj = ResourceManager.GetObject("UnvisibleGraph", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] VisibleGraph {
            get {
                object obj = ResourceManager.GetObject("VisibleGraph", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
