//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaussiansModel.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GaussiansModel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Import file.
        /// </summary>
        internal static string ByPatternReaderName {
            get {
                return ResourceManager.GetString("ByPatternReaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export string.
        /// </summary>
        internal static string ExportStringName {
            get {
                return ResourceManager.GetString("ExportStringName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export prn.
        /// </summary>
        internal static string ExportToPrn {
            get {
                return ResourceManager.GetString("ExportToPrn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extremums.
        /// </summary>
        internal static string ExtremumParameterName {
            get {
                return ResourceManager.GetString("ExtremumParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Values.
        /// </summary>
        internal static string InputArray {
            get {
                return ResourceManager.GetString("InputArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input graph.
        /// </summary>
        internal static string InputChartName {
            get {
                return ResourceManager.GetString("InputChartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Count inflection.
        /// </summary>
        internal static string InputCountInflection {
            get {
                return ResourceManager.GetString("InputCountInflection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Distance x.
        /// </summary>
        internal static string InputDistanceX {
            get {
                return ResourceManager.GetString("InputDistanceX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Distance y.
        /// </summary>
        internal static string InputDistanceY {
            get {
                return ResourceManager.GetString("InputDistanceY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End.
        /// </summary>
        internal static string InputEndX {
            get {
                return ResourceManager.GetString("InputEndX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Graphs collection.
        /// </summary>
        internal static string InputGraphsCollection {
            get {
                return ResourceManager.GetString("InputGraphsCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max angle.
        /// </summary>
        internal static string InputMaxAngle {
            get {
                return ResourceManager.GetString("InputMaxAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max error.
        /// </summary>
        internal static string InputMaxError {
            get {
                return ResourceManager.GetString("InputMaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max steps.
        /// </summary>
        internal static string InputMaxSteps {
            get {
                return ResourceManager.GetString("InputMaxSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max tangent.
        /// </summary>
        internal static string InputMaxtanValue {
            get {
                return ResourceManager.GetString("InputMaxtanValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max.
        /// </summary>
        internal static string InputMaxValue {
            get {
                return ResourceManager.GetString("InputMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Min.
        /// </summary>
        internal static string InputMinValue {
            get {
                return ResourceManager.GetString("InputMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Noize point.
        /// </summary>
        internal static string InputNoizePoint {
            get {
                return ResourceManager.GetString("InputNoizePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Min range by Y .
        /// </summary>
        internal static string InputRangeYIgnore {
            get {
                return ResourceManager.GetString("InputRangeYIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Source.
        /// </summary>
        internal static string InputSource {
            get {
                return ResourceManager.GetString("InputSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start.
        /// </summary>
        internal static string InputStartX {
            get {
                return ResourceManager.GetString("InputStartX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Step.
        /// </summary>
        internal static string InputStep {
            get {
                return ResourceManager.GetString("InputStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на String.
        /// </summary>
        internal static string InputString {
            get {
                return ResourceManager.GetString("InputString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Two string.
        /// </summary>
        internal static string InputStringTwo {
            get {
                return ResourceManager.GetString("InputStringTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max point for corretion.
        /// </summary>
        internal static string InputUncorrectPointsValue {
            get {
                return ResourceManager.GetString("InputUncorrectPointsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value.
        /// </summary>
        internal static string InputValueName {
            get {
                return ResourceManager.GetString("InputValueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Graph.
        /// </summary>
        internal static string OutputGraph {
            get {
                return ResourceManager.GetString("OutputGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Graphs.
        /// </summary>
        internal static string OutputGraphs {
            get {
                return ResourceManager.GetString("OutputGraphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max.
        /// </summary>
        internal static string OutputMaxGraph {
            get {
                return ResourceManager.GetString("OutputMaxGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Min.
        /// </summary>
        internal static string OutputMinGraph {
            get {
                return ResourceManager.GetString("OutputMinGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на String.
        /// </summary>
        internal static string OutputString {
            get {
                return ResourceManager.GetString("OutputString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value.
        /// </summary>
        internal static string OutputValue {
            get {
                return ResourceManager.GetString("OutputValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Index.
        /// </summary>
        internal static string OutputValueIndex {
            get {
                return ResourceManager.GetString("OutputValueIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Point graphs.
        /// </summary>
        internal static string PointGraphForeachFunctionName {
            get {
                return ResourceManager.GetString("PointGraphForeachFunctionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By average value.
        /// </summary>
        internal static string SmoothingByAverageFunctionName {
            get {
                return ResourceManager.GetString("SmoothingByAverageFunctionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By distance value.
        /// </summary>
        internal static string SmoothingByDistanceFunctionName {
            get {
                return ResourceManager.GetString("SmoothingByDistanceFunctionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stretch X.
        /// </summary>
        internal static string StretchXChanger {
            get {
                return ResourceManager.GetString("StretchXChanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stretch Y.
        /// </summary>
        internal static string StretchYChanger {
            get {
                return ResourceManager.GetString("StretchYChanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add string.
        /// </summary>
        internal static string StringAddBuilderName {
            get {
                return ResourceManager.GetString("StringAddBuilderName", resourceCulture);
            }
        }
    }
}
